"""The Generation-2 procedural course family.

One broad task family generates every Gen-2 course: expert demonstrations,
DAgger rollouts, validation, test, and the sealed final holdout.  A course is a
pure deterministic function of ``(seed, gate_count)`` -- no global state, no
curriculum ladder -- so a course can be regenerated byte-for-byte from its seed
alone and the same generator provably produced the training and the holdout
geometry.

The family is deliberately broad rather than tuned:

* horizontal turns, left and right, monotone and alternating;
* vertical transitions, climbs and descents, monotone and alternating;
* combined horizontal + vertical (helical) transitions;
* mixed geometry with occasional near-straight recovery segments;
* randomized spacing, entry angle, initial lateral offset and start distance.

Nothing here reads the three retired official circuits, and no pattern is fitted
to any observed Gen-1 failure location.

Course metadata (``spec.as_dict()``) exists for dataset diagnostics ONLY.  It
must never reach the policy input; the policy sees exactly the 35 features of
``onboard_local_transition_v1``.
"""

from __future__ import annotations

import copy
import hashlib
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

import numpy as np

from marine_race_arena.learning.sequence_curriculum import (
    BASE_TRACK,
    SequenceGeometry,
    _atomic_json,
    generate_sequence_track,
)

# The sequence lengths the Gen-2 experiment is defined over.
GEN2_GATE_COUNTS: Tuple[int, ...] = (2, 3, 5, 8, 12, 17, 22)

# Sampling weights for the expert demonstration corpus.  Long courses carry far
# more samples per episode, so the *episode* distribution is tilted toward short
# courses while the *sample* distribution stays broad.
GEN2_DEMO_GATE_WEIGHTS: Dict[int, float] = {
    2: 0.20, 3: 0.20, 5: 0.20, 8: 0.15, 12: 0.12, 17: 0.08, 22: 0.05,
}

GEN2_PATTERNS: Tuple[str, ...] = (
    "straight",
    "turn_left",
    "turn_right",
    "s_curve_left",
    "s_curve_right",
    "climb",
    "descend",
    "vertical_serpent",
    "helix_left",
    "helix_right",
    "alternating_mixed",
    "mixed",
)

# One broad geometric envelope for the whole family.
MAX_TURN_DEG = 45.0
MAX_VERTICAL_STEP_M = 1.60
MIN_SPACING_M = 3.2
MAX_SPACING_M = 8.5
MAX_INITIAL_YAW_ERROR_DEG = 25.0
MAX_INITIAL_LATERAL_OFFSET_M = 1.0
MIN_START_DISTANCE_M = 3.5
MAX_START_DISTANCE_M = 5.5

#: Two gates that are not neighbours in the sequence must stay this far apart.
#: A monotone 45-degree turn at 4 m spacing closes a circle of radius ~5 m, so
#: a long ``turn_right`` course would wrap onto itself and place gate 12 beside
#: gate 3.  That is not a hard course, it is an ambiguous one: the onboard
#: beacon/vision front end cannot tell which gate it is looking at, and even a
#: perfect controller has no legal way to resolve it.  Courses are relaxed
#: until this clearance holds, so difficulty comes from geometry the vehicle
#: can actually perceive.
MIN_NONADJACENT_GATE_SEPARATION_M = 4.0
#: Multiplicative attenuation applied to the turn deltas per relaxation pass.
_RELAXATION_FACTOR = 0.82
_MAX_RELAXATION_PASSES = 24

GEN2_COURSE_FAMILY_VERSION = "gen2_course_family_v1"


@dataclass(frozen=True)
class Gen2CourseSpec:
    """A complete, reproducible description of one Gen-2 course."""

    family_version: str
    seed: int
    gate_count: int
    pattern: str
    spacings_m: Tuple[float, ...]
    turn_deltas_deg: Tuple[float, ...]
    vertical_deltas_m: Tuple[float, ...]
    initial_yaw_error_deg: float
    initial_lateral_offset_m: float
    start_distance_m: float
    #: How many attenuation passes the self-intersection guard needed (0 = none).
    relaxation_passes: int = 0

    @property
    def min_nonadjacent_separation_m(self) -> float:
        return min_nonadjacent_gate_separation_m(
            self.spacings_m, self.turn_deltas_deg, self.vertical_deltas_m
        )

    @property
    def geometry_group(self) -> str:
        return f"{self.gate_count}:{self.pattern}"

    @property
    def total_turn_deg(self) -> float:
        return float(sum(abs(v) for v in self.turn_deltas_deg))

    @property
    def total_vertical_m(self) -> float:
        return float(sum(abs(v) for v in self.vertical_deltas_m))

    @property
    def net_turn_deg(self) -> float:
        return float(sum(self.turn_deltas_deg))

    @property
    def net_vertical_m(self) -> float:
        return float(sum(self.vertical_deltas_m))

    @property
    def turn_reversals(self) -> int:
        signs = [1 if v > 1e-9 else (-1 if v < -1e-9 else 0) for v in self.turn_deltas_deg]
        signs = [s for s in signs if s]
        return sum(1 for a, b in zip(signs, signs[1:]) if a != b)

    @property
    def vertical_reversals(self) -> int:
        signs = [1 if v > 1e-9 else (-1 if v < -1e-9 else 0) for v in self.vertical_deltas_m]
        signs = [s for s in signs if s]
        return sum(1 for a, b in zip(signs, signs[1:]) if a != b)

    def as_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def summary(self) -> Dict[str, Any]:
        """Compact geometry summary for manifests and diagnostics."""
        return {
            "seed": self.seed,
            "gate_count": self.gate_count,
            "pattern": self.pattern,
            "total_turn_deg": round(self.total_turn_deg, 3),
            "net_turn_deg": round(self.net_turn_deg, 3),
            "turn_reversals": self.turn_reversals,
            "total_vertical_m": round(self.total_vertical_m, 3),
            "net_vertical_m": round(self.net_vertical_m, 3),
            "vertical_reversals": self.vertical_reversals,
            "mean_spacing_m": round(float(np.mean(self.spacings_m)), 3) if self.spacings_m else 0.0,
            "min_spacing_m": round(float(np.min(self.spacings_m)), 3) if self.spacings_m else 0.0,
            "max_spacing_m": round(float(np.max(self.spacings_m)), 3) if self.spacings_m else 0.0,
            "initial_yaw_error_deg": round(self.initial_yaw_error_deg, 3),
            "initial_lateral_offset_m": round(self.initial_lateral_offset_m, 3),
            "start_distance_m": round(self.start_distance_m, 3),
            "min_nonadjacent_separation_m": round(self.min_nonadjacent_separation_m, 3)
            if self.gate_count >= 3 else None,
            "relaxation_passes": self.relaxation_passes,
        }

    def content_sha256(self) -> str:
        payload = json.dumps(self.as_dict(), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _course_rng(seed: int, gate_count: Optional[int]) -> np.random.Generator:
    """Derive an independent stream so the same seed at a different length differs."""
    material = f"{GEN2_COURSE_FAMILY_VERSION}|{int(seed)}|{gate_count if gate_count else 'auto'}"
    digest = hashlib.sha256(material.encode("utf-8")).digest()
    return np.random.default_rng(int.from_bytes(digest[:8], "little"))


def _pattern_deltas(
    rng: np.random.Generator, *, gate_count: int, pattern: str
) -> Tuple[Tuple[float, ...], Tuple[float, ...]]:
    n = max(0, gate_count - 1)
    if n == 0:
        return (), ()
    turn_cap = MAX_TURN_DEG
    vertical_cap = MAX_VERTICAL_STEP_M

    if pattern == "straight":
        turns = rng.uniform(-4.0, 4.0, n)
        vertical = rng.uniform(-0.10, 0.10, n)
    elif pattern in ("turn_left", "turn_right"):
        sign = 1.0 if pattern == "turn_left" else -1.0
        turns = sign * rng.uniform(0.35, 1.0, n) * turn_cap
        vertical = rng.uniform(-0.25, 0.25, n) * vertical_cap
    elif pattern in ("s_curve_left", "s_curve_right"):
        lead = 1.0 if pattern == "s_curve_left" else -1.0
        magnitude = rng.uniform(0.45, 1.0, n) * turn_cap
        turns = np.asarray([
            lead * magnitude[i] * (1.0 if i % 2 == 0 else -1.0) for i in range(n)
        ])
        vertical = rng.uniform(-0.35, 0.35, n) * vertical_cap
    elif pattern in ("climb", "descend"):
        sign = -1.0 if pattern == "climb" else 1.0  # z is negative-down
        turns = rng.uniform(-0.35, 0.35, n) * turn_cap
        vertical = sign * rng.uniform(0.40, 1.0, n) * vertical_cap
    elif pattern == "vertical_serpent":
        turns = rng.uniform(-0.35, 0.35, n) * turn_cap
        magnitude = rng.uniform(0.50, 1.0, n) * vertical_cap
        vertical = np.asarray([
            magnitude[i] * (1.0 if i % 2 == 0 else -1.0) for i in range(n)
        ])
    elif pattern in ("helix_left", "helix_right"):
        sign = 1.0 if pattern == "helix_left" else -1.0
        turns = sign * rng.uniform(0.40, 1.0, n) * turn_cap
        vertical_sign = float(rng.choice((-1.0, 1.0)))
        vertical = vertical_sign * rng.uniform(0.40, 1.0, n) * vertical_cap
    elif pattern == "alternating_mixed":
        # Yaw and depth alternate on different phases, so a turn rarely lines up
        # with the vertical step it is paired with.
        turn_magnitude = rng.uniform(0.40, 1.0, n) * turn_cap
        vertical_magnitude = rng.uniform(0.40, 1.0, n) * vertical_cap
        turns = np.asarray([
            turn_magnitude[i] * (1.0 if i % 2 == 0 else -1.0) for i in range(n)
        ])
        vertical = np.asarray([
            vertical_magnitude[i] * (1.0 if (i // 2) % 2 == 0 else -1.0) for i in range(n)
        ])
    else:  # "mixed"
        turns = rng.uniform(-1.0, 1.0, n) * turn_cap
        vertical = rng.uniform(-1.0, 1.0, n) * vertical_cap
        if n >= 5:
            # Keep occasional near-straight recovery segments inside long courses.
            relaxed = rng.choice(n, size=max(1, n // 5), replace=False)
            turns[relaxed] *= 0.12
            vertical[relaxed] *= 0.15

    return tuple(float(v) for v in turns), tuple(float(v) for v in vertical)


def gate_positions(
    spacings_m: Sequence[float],
    turn_deltas_deg: Sequence[float],
    vertical_deltas_m: Sequence[float],
) -> np.ndarray:
    """Integrate the deltas into gate centres, mirroring ``generate_sequence_track``.

    Kept byte-compatible with the materializer (same accumulation order, same
    depth clip) so a validity check here predicts the real track exactly.
    """
    count = len(spacings_m) + 1
    yaw = 0.0
    x = y = 0.0
    z = -4.0
    points = np.zeros((count, 3), dtype=np.float64)
    points[0] = (x, y, z)
    for index in range(1, count):
        yaw += float(turn_deltas_deg[index - 1])
        spacing = float(spacings_m[index - 1])
        x += spacing * math.cos(math.radians(yaw))
        y += spacing * math.sin(math.radians(yaw))
        z = float(np.clip(z + float(vertical_deltas_m[index - 1]), -8.0, -2.0))
        points[index] = (x, y, z)
    return points


def min_nonadjacent_gate_separation_m(
    spacings_m: Sequence[float],
    turn_deltas_deg: Sequence[float],
    vertical_deltas_m: Sequence[float],
) -> float:
    """Closest approach between two gates that are not neighbours in the order."""
    points = gate_positions(spacings_m, turn_deltas_deg, vertical_deltas_m)
    count = len(points)
    if count < 3:
        return float("inf")
    best = float("inf")
    for i in range(count):
        for j in range(i + 2, count):
            best = min(best, float(np.linalg.norm(points[i] - points[j])))
    return best


def _relax_self_intersection(
    spacings: Tuple[float, ...],
    turns: Tuple[float, ...],
    vertical: Tuple[float, ...],
) -> Tuple[Tuple[float, ...], int]:
    """Attenuate turn deltas until non-adjacent gates clear the threshold.

    Deterministic: the same input always yields the same number of passes, so a
    course stays reproducible from its seed.  Only the turns are attenuated --
    shrinking spacing would make the course shorter rather than less ambiguous,
    and shrinking the vertical deltas would remove the climb/descent diversity
    the family exists to provide.
    """
    if len(spacings) < 2:
        return turns, 0
    current = turns
    for passes in range(_MAX_RELAXATION_PASSES + 1):
        separation = min_nonadjacent_gate_separation_m(spacings, current, vertical)
        if separation >= MIN_NONADJACENT_GATE_SEPARATION_M:
            return current, passes
        current = tuple(value * _RELAXATION_FACTOR for value in current)
    return current, _MAX_RELAXATION_PASSES


def sample_gate_count(seed: int, weights: Optional[Mapping[int, float]] = None) -> int:
    """Deterministically choose a gate count for ``seed`` from the demo mixture."""
    table = dict(weights or GEN2_DEMO_GATE_WEIGHTS)
    counts = sorted(table)
    probabilities = np.asarray([table[c] for c in counts], dtype=float)
    probabilities = probabilities / probabilities.sum()
    rng = _course_rng(seed, None)
    return int(rng.choice(counts, p=probabilities))


def sample_course(
    seed: int,
    *,
    gate_count: Optional[int] = None,
    pattern: Optional[str] = None,
    gate_count_weights: Optional[Mapping[int, float]] = None,
) -> Gen2CourseSpec:
    """Return the deterministic Gen-2 course for ``seed`` (and optional length)."""
    if gate_count is None:
        gate_count = sample_gate_count(seed, gate_count_weights)
    gate_count = int(gate_count)
    if gate_count < 1:
        raise ValueError("a course needs at least one gate")

    rng = _course_rng(seed, gate_count)
    if pattern is None:
        pattern = str(rng.choice(GEN2_PATTERNS))
    elif pattern not in GEN2_PATTERNS:
        raise ValueError(f"unknown Gen-2 pattern {pattern!r}")

    turns, vertical = _pattern_deltas(rng, gate_count=gate_count, pattern=pattern)
    spacings = tuple(
        float(v) for v in rng.uniform(MIN_SPACING_M, MAX_SPACING_M, max(0, gate_count - 1))
    )
    turns, relaxation_passes = _relax_self_intersection(spacings, turns, vertical)
    return Gen2CourseSpec(
        family_version=GEN2_COURSE_FAMILY_VERSION,
        seed=int(seed),
        gate_count=gate_count,
        pattern=pattern,
        spacings_m=spacings,
        turn_deltas_deg=turns,
        vertical_deltas_m=vertical,
        initial_yaw_error_deg=float(
            rng.uniform(-MAX_INITIAL_YAW_ERROR_DEG, MAX_INITIAL_YAW_ERROR_DEG)
        ),
        initial_lateral_offset_m=float(
            rng.uniform(-MAX_INITIAL_LATERAL_OFFSET_M, MAX_INITIAL_LATERAL_OFFSET_M)
        ),
        start_distance_m=float(rng.uniform(MIN_START_DISTANCE_M, MAX_START_DISTANCE_M)),
        relaxation_passes=int(relaxation_passes),
    )


def materialize_course(
    spec: Gen2CourseSpec,
    output_path: str | Path,
    *,
    frames_per_sec: bool | int = False,
    base_track: str | Path = BASE_TRACK,
    race_name: Optional[str] = None,
) -> Path:
    """Write ``spec`` to a runnable, current-free track JSON and return the path."""
    sequence = SequenceGeometry(
        stage="GEN2",
        source="gen2_course_family",
        pattern=spec.pattern,
        seed=spec.seed,
        gate_count=spec.gate_count,
        spacings_m=spec.spacings_m,
        turn_deltas_deg=spec.turn_deltas_deg,
        vertical_deltas_m=spec.vertical_deltas_m,
        initial_yaw_error_deg=spec.initial_yaw_error_deg,
        initial_lateral_offset_m=spec.initial_lateral_offset_m,
    )
    target = generate_sequence_track(sequence, output_path, base_track=base_track)
    data = json.loads(target.read_text(encoding="utf-8"))

    first = data["gates"][0]
    direction = first["passage_direction"]
    start = [
        float(first["position"][0]) - spec.start_distance_m * float(direction[0]),
        float(first["position"][1])
        - spec.start_distance_m * float(direction[1])
        + spec.initial_lateral_offset_m,
        float(first["position"][2]),
    ]
    data["start"]["position"] = [round(value, 5) for value in start]
    data["participants"][0]["spawn"] = copy.deepcopy(data["start"])
    data["participants"][0]["controller"] = "gen2_learned_recurrent"

    path_positions = [data["start"]["position"], *(gate["position"] for gate in data["gates"])]
    data["track"]["declared_length_m"] = round(
        sum(math.dist(a, b) for a, b in zip(path_positions, path_positions[1:])), 3
    )
    data["track"]["length_tolerance_m"] = max(2.0, spec.gate_count * 0.6)

    xs = [p[0] for p in path_positions]
    ys = [p[1] for p in path_positions]
    zs = [p[2] for p in path_positions]
    data["world"]["bounds"] = {
        "x_min": min(xs) - 9.0, "x_max": max(xs) + 9.0,
        "y_min": min(ys) - 9.0, "y_max": max(ys) + 9.0,
        "z_min": min(zs) - 3.0, "z_max": max(zs) + 3.0,
    }
    data["race"]["name"] = race_name or f"Gen2 {spec.geometry_group} seed{spec.seed}"
    data["race"]["max_duration_s"] = max(120, int(spec.gate_count * 45))
    data["holoocean_frames_per_sec"] = frames_per_sec
    # Diagnostics only.  Never an observation input.
    data["gen2_course"] = spec.as_dict()
    data.pop("sequence_curriculum", None)

    # Reuse the retrying atomic writer: Windows can briefly deny replacement
    # while HoloOcean or the indexer releases a just-created track.
    _atomic_json(target, data)
    return target


def track_sha256(path: str | Path) -> str:
    """SHA-256 of a materialized track file (byte-exact)."""
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def family_diversity_report(specs: Sequence[Gen2CourseSpec]) -> Dict[str, Any]:
    """Aggregate geometry statistics used to prove the corpus is actually diverse."""
    if not specs:
        return {"courses": 0}
    patterns: Dict[str, int] = {}
    gate_counts: Dict[str, int] = {}
    for spec in specs:
        patterns[spec.pattern] = patterns.get(spec.pattern, 0) + 1
        gate_counts[str(spec.gate_count)] = gate_counts.get(str(spec.gate_count), 0) + 1
    net_turns = np.asarray([s.net_turn_deg for s in specs])
    net_vertical = np.asarray([s.net_vertical_m for s in specs])
    return {
        "courses": len(specs),
        "unique_seeds": len({s.seed for s in specs}),
        "unique_geometry_sha256": len({s.content_sha256() for s in specs}),
        "patterns": dict(sorted(patterns.items())),
        "gate_counts": dict(sorted(gate_counts.items(), key=lambda kv: int(kv[0]))),
        "left_turning_courses": int((net_turns > 5.0).sum()),
        "right_turning_courses": int((net_turns < -5.0).sum()),
        "near_straight_courses": int((np.abs(net_turns) <= 5.0).sum()),
        "climbing_courses": int((net_vertical < -0.5).sum()),
        "descending_courses": int((net_vertical > 0.5).sum()),
        "level_courses": int((np.abs(net_vertical) <= 0.5).sum()),
        "courses_with_turn_reversals": int(sum(1 for s in specs if s.turn_reversals > 0)),
        "courses_with_vertical_reversals": int(sum(1 for s in specs if s.vertical_reversals > 0)),
        "total_turn_deg": {
            "mean": round(float(np.mean([s.total_turn_deg for s in specs])), 3),
            "max": round(float(np.max([s.total_turn_deg for s in specs])), 3),
        },
        "total_vertical_m": {
            "mean": round(float(np.mean([s.total_vertical_m for s in specs])), 3),
            "max": round(float(np.max([s.total_vertical_m for s in specs])), 3),
        },
    }
