"""Capture a HoloOcean screenshot of the configured environment (VISUALIZATION ONLY).

This launches HoloOcean purely to save an RGB frame of an existing official track
for use as a manuscript figure. It is deliberately NOT a benchmark run:

* it uses an existing track and configuration unchanged;
* it never constructs a referee, never scores, and writes no result artifact;
* it does not belong to the 78-run performance matrix and no claim is derived
  from it.

It requires HoloOcean to be installed (``pip install holoocean`` and the Ocean
package). On a machine without HoloOcean it exits with a clear message instead of
producing anything.

Example::

    python -m marine_race_arena.scripts.capture_environment_screenshot \
        --track marine_race_arena/tracks/marine_race_horseshoe_bay.json \
        --out article/figures/holoocean_environment.png \
        --approach-seconds 6.0
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from marine_race_arena.arena.arena_builder import ArenaBuilder
from marine_race_arena.config.loader import load_track_config
from marine_race_arena.participants.participant import RaceParticipant
from marine_race_arena.scripts.run_marine_race import _mission_info, _vector3

DEFAULT_TRACK = "marine_race_arena/tracks/marine_race_horseshoe_bay.json"
DEFAULT_OUT = "article/figures/holoocean_environment.png"


def _require_holoocean() -> None:
    try:
        import holoocean  # noqa: F401
    except Exception:
        print(
            "HoloOcean is not installed in this environment, so a photo-real "
            "render cannot be captured here. Install HoloOcean and its Ocean "
            "package, then re-run this script on that machine. (The manuscript "
            "ships a schematic of the task generated by "
            "article/figures/generate_figures.py in the meantime.)",
            file=sys.stderr,
        )
        raise SystemExit(2)


def capture(track: str, out: str, approach_seconds: float, headless: bool) -> int:
    _require_holoocean()
    from marine_race_arena.adapters import select_adapter

    config = load_track_config(track, benchmark_task="clean_gate", current_profile="none", seed=0)
    arena = ArenaBuilder(config, seed=0).build()
    base = config.participants[0]
    spawn = base.spawn or {}
    participant = RaceParticipant(
        config=base,
        controller=_HoldController(),
        position=tuple(_vector3(spawn.get("position", config.start.position))),
        rotation_rpy_deg=tuple(_vector3(spawn.get("rotation_rpy_deg", config.start.rotation_rpy_deg))),
    )
    participants = {base.id: participant}

    adapter = select_adapter(
        adapter_name="holoocean",
        config=config,
        arena=arena,
        allow_fallback=False,   # visualization must use the real engine
        headless=headless,
        record=False,
        seed=0,
    )
    try:
        adapter.spawn_participants(participants)
        adapter.reset()
        adapter.spawn_visual_gates(arena.visual_gates)
        participant.controller.reset(_mission_info(config, base.id))

        dt = 0.033
        steps = max(1, int(approach_seconds / dt))
        frame = None
        for _ in range(steps):
            command = participant.controller.step({})
            adapter.apply_command(base.id, command, control_mode="high_level")
            adapter.step(dt)
            sensors = adapter.get_allowed_sensor_data(base.id, base.sensors)
            if "FrontCamera" in sensors:
                frame = sensors["FrontCamera"]
        if frame is None:
            print("No FrontCamera frame was produced; check the sensor profile.", file=sys.stderr)
            return 1
        _save_png(frame, out)
        print(f"Saved visualization-only screenshot to {out}")
        return 0
    finally:
        adapter.close()


class _HoldController:
    """Gentle forward/align command so the vehicle approaches the first gate."""

    uses_ground_truth = False

    def reset(self, mission_info) -> None:
        del mission_info

    def step(self, observation) -> dict:
        del observation
        return {"surge": 0.25, "sway": 0.0, "heave": 0.0, "yaw": 0.0}

    def close(self) -> None:
        pass


def _save_png(frame, out: str) -> None:
    import numpy as np
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    image = np.asarray(frame)
    if image.ndim == 3 and image.shape[2] == 4:
        image = image[:, :, :3]
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    fig = plt.figure(figsize=(4.0, 3.0))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.imshow(image.astype("uint8"))
    ax.axis("off")
    fig.savefig(out, dpi=220)
    plt.close(fig)


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--track", default=DEFAULT_TRACK)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--approach-seconds", type=float, default=6.0)
    parser.add_argument("--headless", action=argparse.BooleanOptionalAction, default=True)
    args = parser.parse_args(argv)
    return capture(args.track, args.out, args.approach_seconds, args.headless)


if __name__ == "__main__":
    raise SystemExit(main())
